name: ai-generated-app

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: gitlab-pr-ai-reviewer
    ports:
      - "3001:3001" # Backend API and Frontend
      - "5173:3001" # Frontend alias (maps to same port)
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:5173
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.com}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SQLITECLOUD_URL=${SQLITECLOUD_URL}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-change-this-in-production}
      - REVIEW_AUTO_POST=${REVIEW_AUTO_POST:-false}
      - REVIEW_MIN_SCORE=${REVIEW_MIN_SCORE:-7}
      - REVIEW_MAX_FILES=${REVIEW_MAX_FILES:-20}
      - REVIEW_MAX_LINES=${REVIEW_MAX_LINES:-1000}
    volumes:
      # Removed local database.sqlite mount - using SQLiteCloud instead
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional - for development with hot reload)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: gitlab-pr-ai-reviewer-dev
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:5173
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.com}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SQLITECLOUD_URL=${SQLITECLOUD_URL}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-change-this-in-production}
      - REVIEW_AUTO_POST=${REVIEW_AUTO_POST:-false}
      - REVIEW_MIN_SCORE=${REVIEW_MIN_SCORE:-7}
      - REVIEW_MAX_FILES=${REVIEW_MAX_FILES:-20}
      - REVIEW_MAX_LINES=${REVIEW_MAX_LINES:-1000}
    volumes:
      - .:/app
      - /app/node_modules
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

  # Nginx reverse proxy (optional - for production)
  nginx:
    image: nginx:alpine
    container_name: gitlab-pr-ai-reviewer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - production

volumes:
  app_data:
    driver: local

networks:
  app-network:
    driver: bridge
